version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - DeflatedPickle
  assignees:
  - DeflatedPickle
  labels:
  - dependencies
  - dependabot
  ignore:
  - dependency-name: net.minecraftforge.gradle:ForgeGradle
    versions:
    - 4.0.15
